name: 'Cloud Run Deploy'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  serviceName:
    description: 'Name of image to push'
    required: true
  projectId:
    description: 'Google Cloud project ID'
    required: true
  serviceAccount:
    description: 'Email of service account to use during deploy'
    required: true
  runtimeServiceAccount:
    description: 'Email of service account to be assumed by service'
    required: true
  region:
    description: 'Google Cloud region to deploy'
    required: false
  concurrency:
    description: 'Max concurrent requests to container'
    required: false
  maxInstances:
    description: 'Max number of containers'
    required: false
