name: 'Jekyll Custom Build'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  directory:
    description: 'Directory in your GitHub workspace containing Jekyll site'
    required: false
  outputDirectory:
    description: 'Directory in which build will output'
    required: false
